[lrgen] Suppoprt grammar name deduction; make --grm optional.
Details

  This change updates the lrgren tool to make the '--grm' argument
  optional.  If the '--grm' argument is not provided, the last
  component of the '--directory' specification will be used as the
  grammar name.

  Additionally, the '--help' text is elaborated, and a few invocation
  examples are provided.

  Furthermore, 'lrgen' is now delivered as part of the build process.

  Finally, some additional help text has been added to resolve issues
  with invoking lrstar & dfa, as well as the semantics for finding the
  executables.

Testing

      source ~/lrstar/lrstar/scripts/setup \
        --build-type debug \
        --bod /tmp/lrstar &&  \
      cd ${LRSTAR_DIR}

      rm -rf ${LRSTAR_BUILD_DIR}        # A really clean build for testing.

      lrstar-build -j 20 clean
      lrstar-build -j 20
      ${LRSTAR_DIR}/scripts/precommit-test

      source ~/lrstar/lrstar/scripts/setup \
        --build-type release \
        --bod /tmp/lrstar &&  \
      cd ${LRSTAR_DIR}

      lrstar-build -j 20 clean
      lrstar-build -j 20
      ${LRSTAR_DIR}/scripts/precommit-test

   <open a new shell prompt, and attempt to use lrgen>

      /tmp/lrstar/release/usr/local/bin/lrgen \
        --directory <root>/lrstar/lrstar/grammars/ANTLR
      fatal: lrstar not found.  See --help.

      PATH=${PATH}:/tmp/lrstar/release/usr/local/bin

      /tmp/lrstar/release/usr/local/bin/lrgen \
        --directory <root>/lrstar/lrstar/grammars/ANTLR

      LRSTAR 24.0.017 32b Copyright Paul B Mann.
      ANTLR.grm
      Grammar      213 rules, 43 terminals, 126 nonterminals.
      States       305 states in LALR(1) state machine.
                   148 states when using shift-reduce actions.
      Conflicts      4 states, 4 shift-reduce, 2 reduce-reduce.
                  rows   cols          matrix       list      vect     total
      B matrix      51 x   38 x 1 =     1,938 ->     169 +     234 =     403
      T matrix       9 x   38 x 2 =       684 ->     402 +     191 =     593
      N matrix      29 x   76 x 2 =     4,408 ->   1,038 +     509 =   1,547
      R matrix       9 x   14 x 1 =       121 ->     121 +     339 =     460
      Total                                        1,730 +   1,273 =   3,003
      0 min 0.011 sec, 31.416 MB, 0 warnings, 0 errors.
      DFA 24.0.016 32b Copyright Paul B Mann.
      ANTLR.lgr
      Grammar     1603 rules, 256 terminals, 63 nonterminals.
      States      5338 states before converting to a DFA.
                   136 states in final DFA state machine.
      Conflicts      0 states, 0 shift-reduce, 0 reduce-reduce.
                  rows   cols          matrix       list      vect     total
      T matrix     113 x   57 x 1 =     6,441 ->   6,441 +     664 =   7,105
      0 min 0.095 sec, 38.784 MB, 0 warnings, 0 errors.

diff --git a/scripts/lrgen b/scripts/lrgen
--- a/scripts/lrgen
+++ b/scripts/lrgen
@@ -9,7 +9,11 @@ set -o errexit;
 
 SCRIPT="${BASH_SOURCE[0]}"
 SRC_DIR=$(dirname "${SCRIPT}");
-source $(readlink -f "${SRC_DIR}/functions");
+if [ ! -z "${LRSTAR_DIR}" ]; then
+    # Development environment being used.
+    # Resolve LRSTAR and DFA with developmental shell functions.
+    source $(readlink -f "${SRC_DIR}/functions");
+fi;
 
 LRSTAR="${LRSTAR:-lrstar}";
 DFA="${DFA:-dfa}";
@@ -23,17 +27,15 @@ function _help()
 {
     cat <<EOF
 
-lrgen [-d <directory>               |
-       --directory <directory>      |
-       -g          <grm-name>       |
-       --grm       <grm-name>       |
-       -G          <lrstar options> |
-       --grmopt    <lrstar options> |
-       -L          <dfa options>    |
-       --lgropt    <dfa options>]...
+lrgen (-d <directory> | --directory) <directory>  |
+      [(-g | --grm) <grm-name>                    |
+       (-G | --grmopt) <lrstar options>           |
+       (-L | --lgropt) <dfa options>]
 
-  This tool is a wrapper for invoking lrstar on a syntax grammar & dfa
-  on a lexcical grammar.  The syntax grammar must exist, but the
+Details:
+
+  This tool is a wrapper for invoking both lrstar on a syntax grammar
+  & dfa on a lexcical grammar.  The syntax grammar must exist, but the
   lexical grammar is not required.
 
   If the lexical grammar is not supplied, then the user is responsible
@@ -43,6 +45,81 @@ lrgen [-d <directory>               |
   Both the syntax and lexcial grammars must reside in the same
   directory.  The files generated by lrstar and dfa will be placed
   into the same directory as the grammar files.
+
+  The files generated by lrstar and dfa will be placed into the
+  directory supplied for '--directory'.
+
+  -d | --directory  (required)
+
+    This is used to specify the directory that contains the 'grm' and,
+    optionally, the 'lgr' grammars.
+
+  -g | -grm         (optional)
+
+    This specifies the name of both the syntax grammar ('grm') and
+    lexical grammar ('lgr') files.  If not specified, the final
+    component of the '--directory' value will be used.
+
+  -G | -grmopt      (optional)
+
+    This facilitates providing options to the invocation of lrstar for
+    the specified grammar.
+
+  -L | -lgropt      (optional)
+
+    This facilitates providing options to the invocation of dfa for
+    the specified grammar.
+
+
+Environment:
+
+  This tool uses two environment variables -- LRSTAR & DFA -- to
+  execute 'lrstar' and 'dfa' respectively.
+
+  LRSTAR:
+
+    The default value of this variable is 'lrstar'.  If a development
+    environment is being used in the current shell, this will resolve
+    to the shell function 'lrstar', and that will refer to the version
+    built from the source tree.
+
+    If a developemnt environment is not being used, it will resolve to
+    an on-disk file that must be in the path.  If lrstar is not in the
+    path, either ensure it is in the path, or set LRSTAR to the full
+    path of the lrstar executable.
+
+  DFA
+
+    The default value of this variable is 'dfa'.  If a development
+    environment is being used in the current shell, this will resolve
+    to the shell function 'dfa', and that will refer to the version
+    built from the source tree.
+
+    If a developemnt environment is not being used, it will resolve to
+    an on-disk file that must be in the path.  If dfa is not in the
+    path, either ensure it is in the path, or set DFA to the full
+    path of the dfa executable.
+
+
+Examples:
+
+  lrgen --directory ${LRSTAR_DIR}/grammars/C11 -grm C11
+  lrgen -d ${LRSTAR_DIR}/grammars/C11
+
+    Generate tables for syntax & lexical grammars of C11.
+
+
+  lrgen -d ${LRSTAR_DIR}/examples/LRK --grmopt "k=100 st d"
+
+    Generate tables for syntax and lexical grammars of LR(*)
+    parsing example.
+
+
+  lrgen -d ${LRSTAR_DIR}/grammars/ALGOL60 -G "ast o"
+
+    Generate tables for syntax grammar of ALGOL60.
+    There is no lexical grammar provided for this grammar.
+
 
 EOF
 }
@@ -57,8 +134,40 @@ function fatal ()
 }
 
 
+# Produce an absolute pathname of the 'grm' file.
+#
+#  lrstar does not properly deal with full pathnames on the command
+#  line; it uses the full pathname rather than just the grammar name.
+#  Be sure to extract only the basename when used with lrstar.
+#
+function grm_filename ()
+{
+    local directory="${1}";
+    local grm_name="${2}";
+
+    echo "${directory}/${grm_name}.grm";
+}
+
+
+# Produce an absolute pathname of the 'lgr' file.
+#
+#  dra does not properly deal with full pathnames on the command line;
+#  it uses the full pathname rather than just the grammar name.  Be
+#  sure to extract only the basename when used with dfa.
+#
+function lgr_filename ()
+{
+    local directory="${1}";
+    local grm_name="${2}";
+
+    echo "${directory}/${grm_name}.lgr";
+}
+
+
 function validate_options()
 {
+    local grm;
+
     DIRECTORY=$(readlink -f "${DIRECTORY}");
     if [ -z "${DIRECTORY}" ] ; then
         _help;
@@ -68,44 +177,53 @@ function validate_options()
         fatal "--directory value, '${DIRECTORY}', is not a directory.";
     fi;
 
+    # invariant:
+    #
+    #   ${DIRECTORY} is the absolute pathname of the directory
+    #   supplied on the command line.
+
     if [ -z "${GRM}" ] ; then
-        _help;
-        echo -e "\n";
-        fatal "Name of syntax grammar file must be specified.";
+        # Infer grammar name from directory name.
+        #
+        # If the grammar name has not been supplied, assume it is the
+        # same as the directory name.
+        #
+        GRM=$(basename "${DIRECTORY}");
     fi;
 
+
+    grm=$(grm_filename "${DIRECTORY}" "${GRM}");
+    if [ ! -r "${grm}" ] ; then
+        fatal "'${GRM}' is not a readable file.";
+    fi;
+
+    # Validate that lrstar and dfa are both executable.
     if ! (${LRSTAR} 2>&1) >/dev/null; then
-        local msg="${LRSTAR} not found.\nPut 'lrstar' in the path, or set LRSTAR in the environment to its path.";
-        fatal "${msg}";
+        fatal "${LRSTAR} not found.  See --help.\n";
     fi;
 
     if ! (${DFA} 2>&1) >/dev/null; then
-        local msg="${DFA} not found.\nPut 'dfa' in the path, or set DFA in the environment to its path.";
-        fatal "${msg}";
+        fatal "${DFA} not found.  See --help.\n";
     fi;
 }
 
 
 function process_grammars()
 {
-    local grm="${GRM}.grm";
-    local lgr="${GRM}.lgr";
+    local grm=$(basename $(grm_filename "${DIRECTORY}" "${GRM}"));
+    local lgr=$(basename $(lgr_filename "${DIRECTORY}" "${GRM}"));
 
-    if [ -f "${grm}" ] ; then
-        if ${LRSTAR} "${grm}" ${GRMOPT}; then
-            # LRSTAR has run successfully.  Next, run DFA if a lexical
-            # grammar exists.
-            if [ -f "${lgr}" ] ; then
-                local dfa=""
-                if ! ${DFA} ${lgr} ${LGROPT}; then
-                    fatal "'${DFA} ${lgr} ${LGROPT}' failed.";
-                fi;
+    if ${LRSTAR} "${grm}" ${GRMOPT}; then
+        # LRSTAR has run successfully.  Next, run DFA if a lexical
+        # grammar exists.
+        if [ -r "${lgr}" ] ; then
+            local dfa=""
+            if ! ${DFA} ${lgr} ${LGROPT}; then
+                fatal "'${DFA} ${lgr} ${LGROPT}' failed.";
             fi;
-        else
-            fatal "'${LRSTAR} "${grm}" ${GRMOPT}' failed.";
         fi;
     else
-        fatal "${DIRECTORY}/${grm} is not a regular file.";
+        fatal "'${LRSTAR} "${grm}" ${GRMOPT}' failed.";
     fi;
 }
 
